Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    #extra-css: # if you wanted to add extra CSS (like changing the default coloring), uncomment and add it here
            #- css/zapdos.css  # example - location relative to your "doc/content" directory
Extensions:
    MooseDocs.extensions.navigation:
        name: CRANE
        repo: https://github.com/lcpp-org/crane
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                Running CRANE: getting_started/running_crane.md
                #Tutorial: tutorial/tutorial.md
                #Documentation: documentation.menu.md
                #SQA: /sqa/index.md
                #News: news/index.md
                #Help:
                #FAQ: help/faq.md
                #Contact: help/contact_us.md
            Examples:
                Global Examples: examples/crane_examples.md
                Zapdos Examples: examples/zapdos_examples.md
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
        unregister:
            framework: !include ${MOOSE_DIR}/framework/doc/unregister.yml
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml
            crane:
                Reactions: /syntax/Reactions/index.md
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
